---
 - name: Wipe and Start Node
   include: playbooks/reset-and-start1.yml

 - name: Wait for devices
   tasks:
     wait_for:
      host: r1,r2,r3,r4,r5,r6,r7,r8,r9,r10
      state: started
      port: 22
      delay: 30

 - name: Copy Lab
   hosts: r1,r2,r3,r4,r5,r6,r7,r8,r9,r10
   roles: 
    - foundation.lab.1.initial.configs
