---
# tasks file for foundation.lab.1.initial.configs

- name: Preparing Your Lab! Wiping and Re-staring Nodes
  hosts: localhost
  gather_facts: false
  tasks:

   - name: Powering UP!!!
     script: ../scripts/_startnodes.sh
     register: status

   - debug:
      msg: msg="{{ status.stdout }}"

- name: Wait for Connection, this could take a while depending on your system, prepare some coffee first
  hosts: router_group1
  gather_facts: false
  tasks:
   
   - name: Waiting! but not in vain!
     wait_for_connection:
      delay: 60
      timeout: 600
