---
 - name: Copy INE-CCIE LAB to Lab Directory
   hosts: localhost
   connection: local
   gather_facts: False
   become: yes
   tasks:
   
    - name: Copy Lab to Eve-ng Lab Folder
      copy:
       src: ../labs/INE_CCIE.unl
       dest: /opt/unetlab/labs/INE_CCIE.unl
       mode: 777
       
    - name: Make lab directory tree readable
      file:
       path: /opt/unetlab/labs
       mode: u=rwX,g=rX,o=rX
       recurse: yes

    - name: Update /etc/hosts for the lab ip address
      blockinfile:
       path: /etc/hosts
       state: present
       insertafter: EOF
       block: |
          192.168.1.101 r1
          192.168.1.102 r2
          192.168.1.103 r3
          192.168.1.104 r4
          192.168.1.105 r5
          192.168.1.106 r6
          192.168.1.107 r7
          192.168.1.108 r8
          192.168.1.109 r9
          192.168.1.110 r10
          192.168.1.101 r11
          192.168.1.112 r12
          192.168.1.113 r13
          192.168.1.114 r14
          192.168.1.115 r15
          192.168.1.116 r16
          192.168.1.117 r17
          192.168.1.118 r18
          192.168.1.119 r19
          192.168.1.120 r20
          192.168.1.121 sw1
          192.168.1.122 sw2
          192.168.1.123 sw3
          192.168.1.124 sw4