---
 - name: Copy INE-CCIE LAB to Lab Directory
   hosts: localhost
   connection: local
   gather_facts: False
   become: yes
   tasks:
   
    - name: Copy Lab
      copy:
       src: ../labs/INE_CCIE.unl
       dest: /opt/unetlab/labs/INE_CCIE.unl
       mode: 777
       
    - name: Make my directory tree readable
      file:
       path: /opt/unetlab/labs
       mode: u=rwX,g=rX,o=rX
       recurse: yes

    - name: Update /etc/hosts for the lab ip address
      blockinfile:
       path: /etc/hosts
       state: present
       insertafter: EOF
       block: |
          192.168.1.101 r1
          192.168.1.102 r2
          192.168.1.103 r3
          192.168.1.104 r4
          192.168.1.105 r5
          192.168.1.106 r6
          192.168.1.107 r7
          192.168.1.108 r8
          192.168.1.109 r9
          192.168.1.110 r10
          192.168.1.111 sw1
          192.168.1.112 sw2
          192.168.1.113 sw3
          192.168.1.114 sw4