---
 - name: Wait for host
   hosts: routers,switch
   tasks:
    - name: Pre-Check if host is reachable
      wait_for:
       port: 22
       state: started
       delay: 300
       sleep: 10
#      register: host_accessible
#      failed_when: False
