---
 - name: Reset and restart Router 1 to 10
   hosts: localhost
   connection: local
   gather_facts: False


 - name: Wait for host
   hosts: 
   tasks:
    - name: Pre-Check if host is reachable
      wait_for:
       hosts: all
       port: 22
       state: started
       delay: 300
       register: host_accessible
       failed_when: False
       sleep: 10
       hosts: r1