---
 - name: Wiping Config back to default then restarting node
   hosts: localhost
   connection: local
   gather_facts: False
   tasks:

    - name: Doing my task master!! Please Wait!!
      script: _startnodes.sh
