---
# tasks file for authenticating.bgp.peerings
 - name: Do not gather hardware facts
   ios_facts:
    gather_subset: min

 - name: Configure R1
   when: ansible_net_hostname == 'R1'
   ios_config:
    src: ./roles/authenticating.bgp.peerings/files/r1.txt
    save_when: modified

 - name: Configure R2
   when: ansible_net_hostname == 'R2'
   ios_config:
    src: ./roles/authenticating.bgp.peerings/files/r2.txt
    save_when: modified
